/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "admin-auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "hedgeco-database": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "hedgeco-vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "hedgeco-web": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "no-reply-email-service": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}