/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "adminAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "hedgecoDatabase": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "hedgecoVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "hedgecoWeb": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "noReplyEmailService": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "userAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}