/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedArticlesRouteImport } from './routes/_authed/articles.route'
import { Route as AuthedArticlesIndexImport } from './routes/_authed/articles.index'
import { Route as AuthedArticlesArticleIdImport } from './routes/_authed/articles.$articleId'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedArticlesRouteRoute = AuthedArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedArticlesIndexRoute = AuthedArticlesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedArticlesRouteRoute,
} as any)

const AuthedArticlesArticleIdRoute = AuthedArticlesArticleIdImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => AuthedArticlesRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/_authed/articles': {
      id: '/_authed/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthedArticlesRouteImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/articles/$articleId': {
      id: '/_authed/articles/$articleId'
      path: '/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof AuthedArticlesArticleIdImport
      parentRoute: typeof AuthedArticlesRouteImport
    }
    '/_authed/articles/': {
      id: '/_authed/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof AuthedArticlesIndexImport
      parentRoute: typeof AuthedArticlesRouteImport
    }
  }
}

// Create and export the route tree

interface AuthedArticlesRouteRouteChildren {
  AuthedArticlesArticleIdRoute: typeof AuthedArticlesArticleIdRoute
  AuthedArticlesIndexRoute: typeof AuthedArticlesIndexRoute
}

const AuthedArticlesRouteRouteChildren: AuthedArticlesRouteRouteChildren = {
  AuthedArticlesArticleIdRoute: AuthedArticlesArticleIdRoute,
  AuthedArticlesIndexRoute: AuthedArticlesIndexRoute,
}

const AuthedArticlesRouteRouteWithChildren =
  AuthedArticlesRouteRoute._addFileChildren(AuthedArticlesRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedArticlesRouteRoute: typeof AuthedArticlesRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedArticlesRouteRoute: AuthedArticlesRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/articles': typeof AuthedArticlesRouteRouteWithChildren
  '/articles/$articleId': typeof AuthedArticlesArticleIdRoute
  '/articles/': typeof AuthedArticlesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/articles/$articleId': typeof AuthedArticlesArticleIdRoute
  '/articles': typeof AuthedArticlesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authed/articles': typeof AuthedArticlesRouteRouteWithChildren
  '/_authed/articles/$articleId': typeof AuthedArticlesArticleIdRoute
  '/_authed/articles/': typeof AuthedArticlesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/logout'
    | '/articles'
    | '/articles/$articleId'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/logout' | '/articles/$articleId' | '/articles'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/logout'
    | '/_authed/articles'
    | '/_authed/articles/$articleId'
    | '/_authed/articles/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LogoutRoute: typeof LogoutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LogoutRoute: LogoutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/logout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/articles"
      ]
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_authed/articles": {
      "filePath": "_authed/articles.route.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/articles/$articleId",
        "/_authed/articles/"
      ]
    },
    "/_authed/articles/$articleId": {
      "filePath": "_authed/articles.$articleId.tsx",
      "parent": "/_authed/articles"
    },
    "/_authed/articles/": {
      "filePath": "_authed/articles.index.tsx",
      "parent": "/_authed/articles"
    }
  }
}
ROUTE_MANIFEST_END */
