FROM oven/bun:1 AS base
WORKDIR /app

COPY ./package.json .
COPY ./bun.lock .

FROM base AS prod-deps
RUN bun install --omit=dev

FROM base AS build-deps
RUN bun install

FROM build-deps AS build
COPY ./databases/hedgeco-database ./databases/hedgeco-database
COPY ./deployments/admin-auth ./deployments/admin-auth
COPY ./deployments/user-auth ./deployments/user-auth
COPY ./deployments/hedgeco-web ./deployments/hedgeco-web
COPY ./libraries/tsconfig ./libraries/tsconfig

WORKDIR /app/deployments/hedgeco-web
RUN bun run build

FROM base AS runtime
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=prod-deps /app/deployments/hedgeco-web/node_modules ./deployments/hedgeco-web/node_modules
COPY --from=build /app/deployments/hedgeco-web/dist ./deployments/hedgeco-web/dist

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000
CMD bun run deployments/hedgeco-web/dist/server/index.mjs