FROM oven/bun:1
WORKDIR /app

COPY ./package.json .
COPY ./bun.lock .

COPY ./databases/hedgeco-database ./databases/hedgeco-database
COPY ./deployments/admin-auth ./deployments/admin-auth
COPY ./deployments/user-auth ./deployments/user-auth
COPY ./deployments/hedgeco-web ./deployments/hedgeco-web
COPY ./libraries/tsconfig ./libraries/tsconfig

RUN bun install

WORKDIR /app/deployments/hedgeco-web
RUN ls -la
RUN bun run build

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000

CMD bun run dist/server/index.mjs